version: "3.8"

services:
  search-engine:
    build: .
    container_name: bunflare
    ports:
      - "3000:3000"
    environment:
      SEARCH_API_KEY: ${SEARCH_API_KEY}
    restart: unless-stopped
